### PR TITLE
Update django guide

### PR DESCRIPTION
**Pull request by blablatdinov**
Hi! Thanks for implementation and post this algorithm!

I'm find inaccuracy in django example: bot token not transform to secret key

https://github.com/swimmwatch/telegram-webapp-auth/blob/9f98e204e351f19b6668ae9391af3f1c04e65984/docs/guide/examples/django.md?plain=1#L10-L12

fastapi:

https://github.com/swimmwatch/telegram-webapp-auth/blob/9f98e204e351f19b6668ae9391af3f1c04e65984/docs/guide/examples/fastapi.md?plain=1#L24-L27

### CODE REVIEW

**Comment by blablatdinov** [comment]
@swimmwatch take a look please

**Comment by swimmwatch** [comment]
@blablatdinov hello! For this example i suppose that user has declared this variable in Django settings file:

`settings.py`
```python
TELEGRAM_BOT_TOKEN=env.str('TELEGRAM_BOT_TOKEN')
TELEGRAM_SECRET_KEY=generate_secret_key(TELEGRAM_BOT_TOKEN)
```

**Comment by blablatdinov** [comment]
@swimmwatch Okay, in this case I revert commit and will add info about `settings.py` content in `docs/guide/examples/django.md`

**Comment by swimmwatch** [comment]
@blablatdinov ok, thanks. Tomorrow I will build release with your changes.

**Pull request merged**
